# Introduction

This project is intended to conduct exploratory data analysis to determine methods of comparing Formula 1 racing drivers during the 2024 season. Currently, F1 fan and media spaces are often embroiled in debate regarding the makings of the best driver, the qualities that contribute to succeeding in the World Drivers Championship over the course of the 24-race season. Former world champions, motorsport experts, and even Electronic Arts’ F1 Game cite varying markers of success from a combination of consistency and experience to fast pace melded with awareness. Considering these numerous quantitative features of driver performance from average lap time to penalty points and external factors, like driver team, race circuit style, and tire strategy, I would like to explore which attributes truly resulted in success in the 2024 World Drivers’ Championship. To guide my investigation, I will frequently need to control certain external variables when measuring true driver performance excellence, like comparing driver standings in the championship across the grid is not the most insightful considering it does not take into account the different speeds of the car they’re driving. As an avid watcher of Formula 1, I’m really interested in pursuing this project to identify and analyze which driver performance traits define and propel some of my favorite drivers.
